version: '3'

vars:
  bucket: 'stitch-tester-bucket'
  key: 'test.bin'

tasks:
  build:
    cmds:
      - go build main.go
  create_file:
    cmds:
      - fallocate -l {{.CLI_ARGS}} {{.key}}
  upload:
    cmds:
      - ./main -bucket {{.bucket}} -key {{.key}} -file {{.key}} {{.CLI_ARGS}}
  s3:remove:
    cmds:
      - aws s3api delete-object --bucket {{.bucket}} --key {{.key}}
  s3:list:
    cmds:
      - aws s3api list-objects --bucket {{.bucket}} | jq
  s3:create:
    cmds:
      - aws s3api create-bucket --bucket {{.bucket}}
